---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    useless: controller
  namespace: useless
  name: useless-function
rules:
- apiGroups:
  - ""
  resources:
  - services
  - events
  verbs:
  - create
  - update
  - patch
  - delete
  - get
  - list
  - watch
- apiGroups:
  - apps
  - extensions
  resources:
  - deployments
  verbs:
  - create
  - update
  - patch
  - delete
  - get
  - list
  - watch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - create
  - update
  - patch
  - delete
  - get
  - list
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - update
  - patch
  - delete
  - get
  - list
  - watch
- apiGroups:
  - alphabetical.useless
  resources:
  - functions
  verbs:
  - create
  - update
  - patch
  - delete
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: useless-function-access
  namespace: useless
subjects:
- kind: ServiceAccount
  name: default
  namespace: useless
roleRef:
  kind: ClusterRole
  name: useless-function
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    useless: controller
  name: useless-controller
  namespace: useless
spec:
  replicas: 2
  selector:
    matchLabels:
      useless: controller
  template:
    metadata:
      labels:
        useless: controller
    spec:
      restartPolicy: Always
      containers:
        - name: useless-controller
          imagePullPolicy: Always
          image: registry.cn-hangzhou.aliyuncs.com/useless/controller:latest
          env:
            - name: ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
